version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.27.9
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"